export interface User {
  id: number;
  name: string;
  email: string;
  phone?: string;
  address?: string;
  role: "DONOR" | "CAREHOME";
  isVerified: boolean;
  registrationNo?: string;
  category?: string;
  profileImage?: string;
  unreadNotifications?: number;
}

export interface InventoryItem {
  id: number;
  itemName: string;
  category: string;
  stockLevel: number;
  reorderLevel: number;
  unit: string;
  itemDescription?: string;
  userId: number;
}

export interface InventoryTableItem {
  id: number;
  name: string;
  category: string;
  stockLevel: number;
  reorderLevel: number;
  unit: string;
}

export interface NeedItem {
  id: number;
  itemName: string;
  requiredQuantity: number;
  currentQuantity: number;
  category: string;
  urgencyLevel: "High" | "Medium" | "Low";
  unit: string;
  userId: number;
  isAutoGenerated?: boolean;
}

export interface NeedTableItem {
  id: number;
  name: string;
  requiredQuantity: number;
  currentQuantity: number;
  shortage: number;
  category: string;
  urgencyLevel: "High" | "Medium" | "Low";
  unit: string;
  userId?: number;
  isAutoGenerated?: boolean;
}

export interface MealDonationSlot {
  id?: number;
  date: Date;
  mealType: "Breakfast" | "Lunch" | "Dinner";
  status: "Available" | "Booked" | "Completed";
  careHomeId: number;
  donorId?: number;
}

export interface CalendarDay {
  date: Date;
  breakfast?: MealDonationSlot;
  lunch?: MealDonationSlot;
  dinner?: MealDonationSlot;
}

export interface CareHome {
  id: number;
  registrationNo: string;
  name: string;
  address: string;
  phone: string;
  email: string;
  category: string;
}

export interface Donation {
  id: number;
  quantity: number;
  date: string;
  status: "pending" | "completed" | "rejected";
  notes?: string;
  donorId: number;
  needId: number;
  need?: NeedItem & { user?: User };
  donor?: User;
}

export interface Chat {
  id: number;
  donorId: number;
  careHomeId: number;
  createdAt: string;
  updatedAt: string;
  careHome?: {
    id: number;
    name: string;
    email: string;
  };
  donor?: {
    id: number;
    name: string;
    email: string;
  };
  messages?: Message[];
  unreadCount?: number; 
}

export interface Message {
  id: number;
  content: string;
  senderId: number;
  chatId: number;
  createdAt: string;
  read: boolean;
  sender?: {
    id: number;
    name: string;
    role: string;
  };
}

export interface Notification {
  id: number;
  userId: number;
  type:
    | "LOW_STOCK"
    | "NEW_DONATION"
    | "DONATION_STATUS"
    | "MEAL_BOOKING"
    | "SYSTEM";
  title: string;
  message: string;
  isRead: boolean;
  relatedId?: number;
  createdAt: Date;
  actionUrl?: string;
}
