import React, { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Plus, Trash, Settings, X, RefreshCw, Bell } from "lucide-react";
import Sidebar from "../components/SideBar";
import Navbar from "../components/NavBarAuth";
import Table from "../components/Table";
import Pagination from "../components/Pagination";
import Button from "../components/AddItemButton";
import { NeedsService, InventoryService } from "../services/api";
import { useAuth } from "../context/AuthContext";
import { toast } from "react-toastify";

interface EnhancedNeedTableItem {
  id: number;
  name: string;
  requiredQuantity: number;
  currentQuantity: number;
  category: string;
  urgencyLevel: "High" | "Medium" | "Low";
  unit: string;
  isAutoGenerated: boolean;
  inventoryStock: number;
}

const NeedListPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [activePage, setActivePage] = useState("need-list");
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [needsData, setNeedsData] = useState<EnhancedNeedTableItem[]>([]);
  const [selectedNeed, setSelectedNeed] =
    useState<EnhancedNeedTableItem | null>(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [lowStockItems, setLowStockItems] = useState<any[]>([]);

  const itemsPerPage = 8;
  const totalPages = Math.ceil(needsData.length / itemsPerPage);

  const fetchNeeds = async () => {
    try {
      if (!user) {
        throw new Error("User not authenticated");
      }

      const [needsData, inventoryData] = await Promise.all([
        NeedsService.getAllNeeds(user.id),
        InventoryService.getAllItems(user.id),
      ]);

      const tableData = needsData.map((item) => {
        const inventoryItem = inventoryData.find(
          (inv) => inv.itemName === item.itemName && inv.unit === item.unit
        );

        return {
          id: item.id,
          name: item.itemName,
          requiredQuantity: item.requiredQuantity,
          currentQuantity: item.currentQuantity,
          category: item.category,
          urgencyLevel: item.urgencyLevel,
          unit: item.unit || "units",
          isAutoGenerated: item.isAutoGenerated || false,
          inventoryStock: inventoryItem?.stockLevel || 0,
        };
      });

      setNeedsData(tableData);

      const lowStock = inventoryData.filter(
        (item) => item.stockLevel < item.reorderLevel
      );
      setLowStockItems(lowStock);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to fetch needs");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchNeeds();
  }, [user]);

  const filteredData = needsData.filter(
    (item) =>
      item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const paginatedData = filteredData.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const handleSearchChange = (query: string) => {
    setSearchQuery(query);
    setCurrentPage(1);
  };

  const handleDeleteNeed = (need: EnhancedNeedTableItem) => {
    setSelectedNeed(need);
    setShowDeleteModal(true);
  };

  const confirmDelete = async () => {
    if (!selectedNeed?.id || !user) return;

    try {
      await NeedsService.deleteNeed(selectedNeed.id, user.id);
      setNeedsData((prevData) =>
        prevData.filter((item) => item.id !== selectedNeed.id)
      );
      setShowDeleteModal(false);
      setSelectedNeed(null);
      toast.success("Need deleted successfully!");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete need");
      toast.error("Failed to delete need");
    }
  };

  const generateNeedsFromInventory = async () => {
    if (!user) return;

    setRefreshing(true);
    try {
      const inventoryItems = await InventoryService.getAllItems(user.id);

      for (const item of inventoryItems) {
        if (item.stockLevel < item.reorderLevel) {
          const shortage = item.reorderLevel - item.stockLevel;

          const existingNeed = needsData.find(
            (n) => n.name === item.itemName && n.unit === item.unit
          );

          if (existingNeed) {
            await NeedsService.updateNeed(
              existingNeed.id,
              {
                requiredQuantity: shortage,
                currentQuantity: 0,
                urgencyLevel: calculateUrgency(
                  item.stockLevel,
                  item.reorderLevel
                ),
              },
              user.id
            );
          } else {
            await NeedsService.createNeed({
              itemName: item.itemName,
              requiredQuantity: shortage,
              currentQuantity: 0,
              category: item.category,
              urgencyLevel: calculateUrgency(
                item.stockLevel,
                item.reorderLevel
              ),
              unit: item.unit,
              userId: user.id,
              isAutoGenerated: true,
            });
          }
        }
      }

      await fetchNeeds();
      toast.success("Needs generated successfully from inventory!");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate needs");
      toast.error("Failed to generate needs from inventory");
    } finally {
      setRefreshing(false);
    }
  };

  const calculateUrgency = (
    stockLevel: number,
    reorderLevel: number
  ): "High" | "Medium" | "Low" => {
    if (reorderLevel === 0) return "Medium";

    const percentage = (stockLevel / reorderLevel) * 100;

    if (percentage < 20) return "High";
    if (percentage < 50) return "Medium";
    return "Low";
  };

  if (loading) return <div className="text-center p-8">Loading needs...</div>;
  if (error)
    return <div className="text-center p-8 text-red-500">Error: {error}</div>;

  return (
    <div className="flex flex-col h-screen bg-gray-50">
      <Navbar />
      <div className="flex flex-1 overflow-hidden pt-20">
        <Sidebar activePage={activePage} />
        <div className="flex-1 flex flex-col overflow-auto p-6 ml-[260px]">
          <h1 className="text-4xl font-bold text-sky-400 mb-6 text-center">
            Need List
          </h1>

          {lowStockItems.length > 0 && (
            <div className="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mb-6">
              <p className="font-medium">
                <Bell size={18} className="inline mr-2" />
                You have {lowStockItems.length} items below reorder level!
              </p>
              <button
                onClick={generateNeedsFromInventory}
                className="mt-2 text-blue-600 hover:text-blue-800 font-medium"
              >
                Generate needs for these items
              </button>
            </div>
          )}

          <div className="flex justify-between items-center mb-6">
            <div className="relative w-full max-w-md">
              <input
                type="text"
                placeholder="Search needs..."
                className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-sky-400"
                value={searchQuery}
                onChange={(e) => handleSearchChange(e.target.value)}
              />
              {searchQuery && (
                <button
                  className="absolute right-3 top-2.5 text-gray-400 hover:text-gray-600"
                  onClick={() => handleSearchChange("")}
                >
                  <X size={18} />
                </button>
              )}
            </div>
            <div className="flex space-x-4">
              <button
                onClick={generateNeedsFromInventory}
                disabled={refreshing}
                className="flex items-center px-4 py-2 bg-[#63C6F7] text-white rounded-md disabled:opacity-50"
              >
                <RefreshCw
                  size={18}
                  className={`mr-2 ${refreshing ? "animate-spin" : ""}`}
                />
                {refreshing ? "Generating..." : "Generate Needs"}
              </button>
              {user?.role === "CAREHOME" && (
                <Link to="/needs/add">
                  <Button text="Add Need" icon={Plus} variant="primary" />
                </Link>
              )}
            </div>
          </div>
          <div className="bg-white rounded-md shadow overflow-hidden">
            <Table<EnhancedNeedTableItem>
              columns={[
                { header: "Item Name", accessor: "name" },
                {
                  header: "Required Qty",
                  accessor: (item: EnhancedNeedTableItem) => (
                    <span className="font-semibold">
                      {item.requiredQuantity} {item.unit}
                    </span>
                  ),
                },
                {
                  header: "Current Qty",
                  accessor: (item: EnhancedNeedTableItem) => (
                    <span
                      className={
                        item.inventoryStock < item.requiredQuantity
                          ? "text-red-600 font-semibold"
                          : "text-green-600 font-semibold"
                      }
                    >
                      {item.inventoryStock} {item.unit}
                    </span>
                  ),
                },
                { header: "Category", accessor: "category" },
                {
                  header: "Urgency",
                  accessor: (item: EnhancedNeedTableItem) => (
                    <span
                      className={`px-2 py-1 rounded-full text-xs ${
                        item.urgencyLevel === "High"
                          ? "bg-red-100 text-red-800"
                          : item.urgencyLevel === "Medium"
                          ? "bg-yellow-100 text-yellow-800"
                          : "bg-green-100 text-green-800"
                      }`}
                    >
                      {item.urgencyLevel}
                    </span>
                  ),
                },
                {
                  header: "Type",
                  accessor: (item: EnhancedNeedTableItem) => (
                    <span
                      className={`px-2 py-1 rounded-full text-xs ${
                        item.isAutoGenerated
                          ? "bg-blue-100 text-blue-800"
                          : "bg-purple-100 text-purple-800"
                      }`}
                    >
                      {item.isAutoGenerated ? "Auto" : "Manual"}
                    </span>
                  ),
                },
                {
                  header: "Actions",
                  accessor: (item: EnhancedNeedTableItem) => (
                    <div className="flex space-x-4">
                      <Link
                        to={`/needs/edit/${item.id}`}
                        className="text-blue-500 hover:text-blue-700"
                      >
                        <Settings size={18} />
                      </Link>
                      {user?.role === "CAREHOME" && (
                        <button
                          className="text-red-500 hover:text-red-700"
                          onClick={() => handleDeleteNeed(item)}
                        >
                          <Trash size={18} />
                        </button>
                      )}
                    </div>
                  ),
                },
              ]}
              data={paginatedData}
            />
          </div>
          {totalPages > 1 && (
            <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={setCurrentPage}
            />
          )}
        </div>
      </div>

      {showDeleteModal && selectedNeed && (
        <div className="fixed inset-0 bg-gray-900 bg-opacity-50 flex justify-center items-center">
          <div className="bg-white p-6 rounded-md shadow-lg">
            <h2 className="text-lg font-bold mb-4">Confirm Delete</h2>
            <p>
              Are you sure you want to delete{" "}
              <strong>{selectedNeed.name}</strong>?
            </p>
            <div className="mt-4 flex justify-end space-x-4">
              <button
                className="px-4 py-2 bg-gray-300 rounded-full"
                onClick={() => setShowDeleteModal(false)}
              >
                Cancel
              </button>
              <button
                className="px-4 py-2 bg-[#63C6F7] text-white rounded-full"
                onClick={confirmDelete}
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default NeedListPage;
